import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const context = await browser.newContext({ storageState: "e2e/.auth/admin.json", viewport: { width: 1400, height: 1000 } });
const page = await context.newPage();
page.setDefaultTimeout(180000);
await page.goto("http://localhost:3001/dashboard/events/positions", { timeout: 240000 });
await page.getByTestId("open-positions-summary").waitFor();
await page.getByRole("radio", { name: "All upcoming" }).click().catch(() => page.getByText("All upcoming").click());
await page.waitForTimeout(500);
console.log("SUMMARY:", await page.getByTestId("open-positions-summary").innerText());
console.log("EVENTS:", await page.getByTestId("open-positions-event").count());
await page.screenshot({ path: "/tmp/open-positions.png", fullPage: false });
const opener = page.getByTestId("open-positions-event").filter({ hasText: "Opener" }).first();
console.log("OPENER EVENT:", (await opener.innerText()).split("\n").slice(0, 6).join(" | "));
await opener.getByRole("link", { name: "Fill" }).first().click();
await page.getByTestId("position-sheet").waitFor({ timeout: 240000 });
await page.waitForTimeout(1500);
console.log("URL:", page.url());
console.log("SHEET:", (await page.getByTestId("position-sheet").innerText()).split("\n").slice(0, 14).join(" | "));
await page.screenshot({ path: "/tmp/position-sheet.png" });
await browser.close();
