import { v } from "convex/values";

/** Validator for every `EmailTemplate`; shared by the email queue and in-app notifications. */
export const emailTemplateValue = v.union(
  v.literal("event_cancelled"),
  v.literal("schedule_published"),
  v.literal("crew_scheduled"),
  v.literal("crew_unscheduled"),
  v.literal("schedule_reminder"),
  v.literal("user_invite"),
  v.literal("password_reset"),
  v.literal("email_verification"),
  v.literal("change_email_confirmation"),
  v.literal("booking_request_received"),
  v.literal("booking_request_admin"),
  v.literal("booking_quote_ready"),
  v.literal("payment_proof_reminder"),
  v.literal("payment_proof_submitted"),
  v.literal("paying_party_added"),
  v.literal("quote_changes_requested"),
  v.literal("quote_updated"),
  v.literal("band_assigned"),
  v.literal("band_event_onboarding_invite"),
  v.literal("band_onboarding_reminder"),
  v.literal("band_payment_confirmation"),
  v.literal("band_payment_completed"),
  v.literal("band_payment_payee_required"),
  v.literal("onboarding_completed"),
  v.literal("onboarding_reminder"),
  v.literal("band_application_received"),
  v.literal("band_application_approved"),
  v.literal("band_application_declined"),
  v.literal("band_application_confirmation"),
  v.literal("crew_application_received"),
  v.literal("crew_application_closed"),
  v.literal("crew_application_confirmation"),
  v.literal("crew_trainee_intro"),
  v.literal("rental_outbound_packed"),
  v.literal("rental_return_processed"),
  v.literal("post_event_album"),
  v.literal("event_comment_mention"),
  v.literal("comment_mention"),
  v.literal("equipment_borrow_request_admin"),
  v.literal("equipment_borrow_request_decided"),
  v.literal("booking_request_declined"),
  v.literal("quote_approved"),
  v.literal("payment_proof_rejected"),
  v.literal("damage_report_admin"),
  v.literal("artist_need_inquiry"),
  v.literal("weekly_digest"),
  v.literal("this_week_at_arbor"),
);

/** Notification-center rows: every email template plus the Home Screen nudge. */
export const notificationTemplateValue = v.union(emailTemplateValue, v.literal("app_install"));
