import { getConvexSiteUrl } from "@/lib/convex-env";
import { fetchCalendarFeed } from "@/lib/calendar-feed";

/**
 * Public, shareable calendar feed at an Arbor-owned URL:
 *   https://arborlive.stanford.edu/events/calendar.ics
 *
 * The ICS is generated by the Convex backend (it owns the data), but we proxy
 * it here so the link people paste into Google/Apple Calendar is our domain
 * rather than a `*.convex.site` host.
 *
 * Caching: calendar clients poll on their own schedule, so a short max-age
 * plus the ICS `X-PUBLISHED-TTL` keeps refreshes prompt without hammering
 * Convex.
 */
export const dynamic = "force-dynamic";

export async function GET() {
  const result = await fetchCalendarFeed(getConvexSiteUrl());

  if (!result.ok) {
    return new Response(result.message, {
      status: result.status,
      headers: { "Content-Type": "text/plain; charset=utf-8" },
    });
  }

  return new Response(result.body, {
    status: 200,
    headers: {
      "Content-Type": "text/calendar; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=300, stale-while-revalidate=600",
      "Content-Disposition": 'inline; filename="arbor-live.ics"',
    },
  });
}
